import { Html, Head, Main, NextScript } from 'next/document';
import Link from 'next/link';
import { Analytics } from '@vercel/analytics/react';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>AI Calorie Counter</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <Link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <body>
        <Main />
        <Analytics />
        <NextScript />
      </body>
    </Html>
  );
}
